#server
server:
  port: 10000

#jdbc
spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: hr
    password: hr

  #jpa
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.Oracle10gDialect
    hibernate:
      #
      #      #jpa ddl-auto
      #        #create: DROP 후 CREATE
      #        #create-drop: DROP 후 CREATE 후 DROP
      #        #update: Entity와 DB 스키마 비교 후 수정 사항 반영(컬럼 삭제는 불가능)
        #validate: Entity와 DB 스키마 비교(다르면 예외 발생)
      ddl-auto: update

    #jpa format
    properties:
      hibernate:
        format_sql: true

  #log
  output:
    ansi:
      enabled: always


# 이미지 용량
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 20MB

      location: c:\\upload
      enabled: true

  #mail
  mail:
    host: smtp.gmail.com
    port: 587
    username: officail.jarjar@gmail.com
    password: sbgccwuycgnfuqkv
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true


  session:
    store-type: redis

  #naver
  security:
    oauth2:
      client:
        registration:
          #naver
          naver:
            client-name: Naver
            client-id: gXIHs8uepXwClgDlEclE
            client-secret: TZXCWxiqmj
            redirect-uri: http://localhost:10000/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name,email,mobile

          #kakao
          kakao:
            client_name: kakao
            client-id: 43642f09d4a5198b6604fe087e1e9b6c
            client-secret: veRDVt2NVsnvEzWFMuTz4sXTP7QI61Xf
            redirect-uri: http://localhost:10000/login/oauth2/code/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: account_email

        provider:
          #naver
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          #kakao
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: kakao_account